export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export LS_COLORS=$LSCOLORS
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export EDITOR='mvim -f'
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=$HOME/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1
export GOPATH=$HOME/Developer/go
#export PATH=/usr/local/bin:$PATH:$GOPATH/bin
